spring:
  profiles:
    active:
      - dev
---
server:
  port: 8002
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/youpingyigou
    username: root
    password: 199761
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
feign:
  hystrix:
    enabled: true 
mybatis-plus:
  mapper-locations: classpath:cn/bofan/youpingyigou/mapper/*Mapper.xml
  type-aliases-package: cn.bofan.youpingyigou.domain,cn.bofan.youpingyigou.query
---
server:
  port: 8003
spring:
  application:
    name: PRODUCT-SERVICE-TEST
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/youpingyigou
    username: root
    password: 199761
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
feign:
  hystrix:
    enabled: true 
mybatis-plus:
  mapper-locations: classpath:cn/bofan/youpingyigou/mapper/*Mapper.xml
  type-aliases-package: cn.bofan.youpingyigou.domain,cn.bofan.youpingyigou.query
---