spring:
  profiles:
    active: dev
---
server:
  port: 8001
spring:
  application:
    name: YOUPINGYIGOU-PLAT
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---
server:
  port: 8002
spring:
  application:
    name: YOUPINGYIGOU-PLAT-TEST
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
---