spring:
  profiles:
    active: dev
---
server:
  port: 9527
spring:
  application:
    name: DAILY-PURCHASE-ZUUL
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  prefix: "/youpingyigou"
  ignored-services: "*"
  routes:
    youpingyigou.serviceId: youpingyigou-plat
    youpingyigou.path: /youpingyigou/**
---
server:
  port: 9528
spring:
  application:
    name: DAILY-PURCHASE-ZUUL
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9528.com
    prefer-ip-address: true
zuul:
  prefix: "/youpingyigou"
  ignored-services: "*"
  routes:
    youpingyigou.serviceId: youpingyigou-plat
    youpingyigou.path: /youpingyigou/**